// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform, kDebugMode;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// 環境別に設定されたFirebase Functions インスタンス（エミュレーター用のみ）
  static FirebaseFunctions? _emulatorFunctions;

  /// 環境別に設定されたFirebase Functions インスタンスを取得
  ///
  /// エミュレーター環境では専用インスタンス、本番・ステージング環境では
  /// 適切なリージョン（asia-northeast1）のインスタンスを返す
  static FirebaseFunctions get functions {
    // エミュレーター環境の場合、設定済みインスタンスを使用
    if (_emulatorFunctions != null) {
      return _emulatorFunctions!;
    }

    return FirebaseFunctions.instanceFor(region: 'asia-northeast1');
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq3cbcgfS8FYAnmFFFs1h1corqodi8Z4w',
    appId: '1:643243619301:android:cfc8b7c45531708896b50c',
    messagingSenderId: '643243619301',
    projectId: 'homii-ai-companion',
    storageBucket: 'homii-ai-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFED3EmOy2a_F36LNft2Nj5tImn8LTVX0',
    appId: '1:643243619301:ios:76c354e26fd5dd6096b50c',
    messagingSenderId: '643243619301',
    projectId: 'homii-ai-companion',
    storageBucket: 'homii-ai-companion.firebasestorage.app',
    iosBundleId: 'global.homii.ai.event.companion.app',
  );

  static Future<void> configureFirebaseServices() async {
      const kUseLocalhost = String.fromEnvironment("USE_LOCALHOST", defaultValue: "0") == "1";
    if (kUseLocalhost) {
      await _configureEmulators();
    }
  }

  /// ローカル開発環境用：Firebaseエミュレーターの設定
  ///
  /// プラットフォーム別に適切なホストアドレスを設定し、
  /// Firebase AuthとFunctionsエミュレーターに接続する
  static Future<void> _configureEmulators() async {
    // プラットフォーム別のホスト設定
    final String host;
    if (kIsWeb) {
      host = 'localhost';
    } else if (defaultTargetPlatform == TargetPlatform.iOS) {
      host = '127.0.0.1';
    } else {
      // Android エミュレーター
      host = '10.0.2.2';
    }

    try {
      // Firebase Auth エミュレーターに接続
      await FirebaseAuth.instance.useAuthEmulator(host, 9098);

      // Firebase Firestore エミュレーターに接続
      FirebaseFirestore.instance.useFirestoreEmulator(host, 8082);

      // Firebase Functions エミュレーターに接続（リージョンを固定してインスタンス化）
      _emulatorFunctions = FirebaseFunctions.instanceFor(region: 'asia-northeast1');
      _emulatorFunctions!.useFunctionsEmulator(host, 5001);

      debugPrint('Firebase エミュレーターに接続しました (Host: $host)');
    } catch (e) {
      debugPrint('Firebase エミュレーター接続エラー: $e');
    }
  }
}
